Engelsk kode eksempel
Skatteetaten/mva-meldingen pull request #11
Opened 2021-04-13 06:51 UTC by KristofferMagelssen

MEMO-3903
Spesielt se gjennom linker til python scriptene som er oversettet at de fortsatt fungerer.

2021-04-21 13:14 UTC, einarhartvigolsenskattetaten reviewed
Submission => Filing

2021-04-21 13:16 UTC, einarhartvigolsenskattetaten reviewed
MvaMelding => VatReturn

2021-04-21 13:17 UTC, einarhartvigolsenskattetaten commented on docs/documentation/test/Steg/load_xml_files.py
> -    with open("./eksempler/konvolutt/" + mvameldinginnsending_filnavn, "r") as file:
MvaMeldingInnsending => VatReturnFiling

2021-04-21 13:22 UTC, einarhartvigolsenskattetaten commented on docs/documentation/test/Steg/validation.py
> +def validate_message(token: dict, xml: str = None):
validate_vat_return

2021-04-21 13:26 UTC, einarhartvigolsenskattetaten commented on docs/documentation/test/innsending-eksempel.ipynb
> +    "    from Steg.validation import validate_message, validate_example_file\n",
validate_vat_return

2021-04-21 13:27 UTC, einarhartvigolsenskattetaten commented on docs/documentation/test/message-submission.ipynb
> +{
rename notebook to "file-vat-return.ipynb"

2021-04-21 13:38 UTC, einarhartvigolsenskattetaten requested changes
Oppdatere navnene som er spredt kommentert, de vil da passe bedre med dokumentasjonen.

2021-04-22 11:41 UTC, KristofferMagelssen commented
Oppdaterte navnene fra kommentarer. @einarhartvigolsenskattetaten 
b3742bf

2021-04-23 09:21 UTC, einarhartvigolsenskattetaten commented on docs/documentation/test/file-vat-return.ipynb
> +    "Test-script to submit a mva message to the app on Altinn3, which is running on the tt02 environment on Altinn Studio."
Og denne typen frittstående mva ord bør kanskje også være vat, men heter det da en vat message? Hmm, burde kanskje vært vat return. Det burde være konsistens i bruken av vat return & vat return filing der vi ellers ville kalt det mva melding eller mva melding innsending.

2021-04-23 11:40 UTC, KristofferMagelssen commented on docs/documentation/test/file-vat-return.ipynb
> +    "Test-script to submit a mva message to the app on Altinn3, which is running on the tt02 environment on Altinn Studio."
Ettersom vi bruker VAT return og VAT return filing ellers, endret jeg til det sånn at det blir konsistent.

2021-04-28 07:24 UTC, einarhartvigolsenskattetaten approved these changes

2021-04-28 07:42 UTC, merged